<?php
    $market = $this->getMarketCode()
?>
<!-- need dynamic php var below for active channel_name -->
<h1>Commercial Real Estate Companies</h1>

<div class="chunk">
    <!-- Tab Nav -->
    <div class="tabs" style="margin-top:15px;">
        <div class="priority-plus">
            <div class="priority-plus__mask" style="display: block;">
                <ul class="tabs__control-list priority-plus__items directory-tabs-alphabet" role="tablist" style="width: 100%;">
                    <li class="tabs__control priority-plus__item" role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="all" aria-controls="slideshow" role="tab" data-toggle="tab">All</a>
                    </li>
                    <li class="tabs__control priority-plus__item" role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#" aria-controls="slideshow" role="tab" data-toggle="tab">0-9</a>
                    </li>


                    <!-- USE PHP FOREACH LOOP HERE -->
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="a" aria-controls="slideshow" role="tab" data-toggle="tab">A</a>
                    </li>
                    <!-- END PHP FOREACH LOOP -->


                    <!-- REMOVE BELOW WHEN PHP LOOP FUNCTIONAL -->
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="b" aria-controls="slideshow" role="tab" data-toggle="tab">B</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="c" aria-controls="slideshow" role="tab" data-toggle="tab">C</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#d" aria-controls="slideshow" role="tab" data-toggle="tab">D</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#e" aria-controls="slideshow" role="tab" data-toggle="tab">E</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#f" aria-controls="slideshow" role="tab" data-toggle="tab">F</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#g" aria-controls="slideshow" role="tab" data-toggle="tab">G</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#h" aria-controls="slideshow" role="tab" data-toggle="tab">H</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#i" aria-controls="slideshow" role="tab" data-toggle="tab">I</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#j" aria-controls="slideshow" role="tab" data-toggle="tab">J</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#k" aria-controls="slideshow" role="tab" data-toggle="tab">K</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#l" aria-controls="slideshow" role="tab" data-toggle="tab">L</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#m" aria-controls="slideshow" role="tab" data-toggle="tab">M</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#n" aria-controls="slideshow" role="tab" data-toggle="tab">N</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#o" aria-controls="slideshow" role="tab" data-toggle="tab">O</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#p" aria-controls="slideshow" role="tab" data-toggle="tab">P</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#q" aria-controls="slideshow" role="tab" data-toggle="tab">Q</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#r" aria-controls="slideshow" role="tab" data-toggle="tab">R</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#s" aria-controls="slideshow" role="tab" data-toggle="tab">S</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#t" aria-controls="slideshow" role="tab" data-toggle="tab">T</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#u" aria-controls="slideshow" role="tab" data-toggle="tab">U</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#v" aria-controls="slideshow" role="tab" data-toggle="tab">V</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#w" aria-controls="slideshow" role="tab" data-toggle="tab">W</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#x" aria-controls="slideshow" role="tab" data-toggle="tab">X</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#y" aria-controls="slideshow" role="tab" data-toggle="tab">Y</a>
                    </li>
                    <li class="tabs__control priority-plus__item " role="presentation">
                        <a class="tabs__control__link directory-tab__link" href="#z" aria-controls="slideshow" role="tab" data-toggle="tab">Z</a>
                    </li>
                    <!-- REMOVE ABOVE WHEN PHP LOOP FUNCTIONAL -->



                    <li class="tabs__control priority-plus__item  priority-plus__item--overflow-trigger">
                        <div class="dropdown js-init" data-init="app/dropdown" style="display: inline-block;">
                            <a href="javascript:void(0);" class="tabs__control__link directory__tab--link dropdown__trigger no-focus" style="margin-right: 5px;">More
                                <i class="icon-down-dir"></i>
                            </a>
                            <div class="dropdown__target dropdown__target--padded dropdown__target--right">
                                <div class="menu-container" style="margin-top: 8px;">
                                    <ul class="menu menu--submenu">
                                        <!-- START FOREACH LOOP AGAIN HERE -->
                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#/" aria-controls="slideshow">A</a>
                                        </li>
                                        <!-- END FOREACH LOOP AGAIN HERE -->


                                        <!-- REMOVE BELOW -->
                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">B</a>
                                        </li>

                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">C</a>
                                        </li>

                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">D</a>
                                        </li>

                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">E</a>
                                        </li>

                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">F</a>
                                        </li>

                                        <li class="priority-plus__overflow-item" role="presentation">
                                            <a class="menu-item submenu-item" href="#" aria-controls="slideshow">G</a>
                                        </li>
                                        <!--REMOVE ABOVE -->

                                    </ul>
                                </div><!-- /.menu-container -->

                            </div><!-- /.dropdown__target -->

                        </div><!-- /.dropdown -->
                    </li>
                    <li class="priority-plus__whitespace"></li>
                </ul>
            </div><!-- /.priority-plus__mask -->
        </div><!-- /.priority-plus -->
    </div><!--/.tabs-->
</div>
<div class="chunk">
    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="a">
            <?= $this->partial('default/datacenter/tab-content/tab-a.phtml'); ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="b">
            <?php // $this->partial('default/datacenter/tab-content/tab-b.phtml'); ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="c">
            <?php // $this->partial('default/datacenter/tab-content/tab-c.phtml'); ?>
        </div>
        <div role="tabpanel" class="tab-pane" id="d">
            <?php // $this->partial('default/datacenter/tab-content/tab-d.phtml'); ?>
        </div>
    </div>

</div>