<script type='text/javascript'>var _sf_startpt=(new Date()).getTime()</script>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="env" content="<?= APPLICATION_ENV?>" >
<?= $this->headTitle() . PHP_EOL; ?>
<base href="<?= $this->serverUrl($this->baseUrl('/')) ?>">
<script type="text/javascript" src="<?= $this->cdnUrl('lib/js/jquery.min.js') ?>"></script>
<script type="text/javascript" src="<?= $this->cdnUrl('static/js/lib/modernizr.custom.min.js') ?>"></script>
<!--[if lte IE 9]>
<script type="text/javascript" src="<?= $this->cdnUrl('static/js/lib/matchMedia.js') ?>"></script>
<script type="text/javascript" src="<?= $this->cdnUrl('static/js/lib/matchMedia.addListener.js') ?>"></script>
<![endif]-->
<script type="text/javascript" src="<?= $this->cdnUrl('static/js/lib/enquire.min.js') ?>"></script>
<!-- Begin comScore Tag -->
<script>
  var _comscore = _comscore || [];
  _comscore.push({ c1: "2", c2: "20214854" });
  (function() {
    var s = document.createElement("script"), el = document.getElementsByTagName("script")[0]; s.async = true;
    s.src = (document.location.protocol == "https:" ? "https://sb" : "http://b") + ".scorecardresearch.com/beacon.js";
    el.parentNode.insertBefore(s, el);
  })();
</script>
<noscript>
  <img src="http://b.scorecardresearch.com/p?c1=2&c2=20214854&cv=2.0&cj=1" />
</noscript>
<!-- End comScore Tag -->
<script type="text/javascript">
    //@todo move this stuff into an include
    setViewport = function(name) {
        $('html').addClass('viewport--' + name);
    }
    unsetViewport = function(name) {
        $('html').removeClass('viewport--' + name);
    }

    var viewports = {};
    viewports.breakpoints = {
        'xs': {
            min: null,
            max: '414px'
        },
        'sm': {
            min: '415px',
            max: '735px'
        },
        'md': {
            min: '736px',
            max: '969px'
        },
        'lg': {
            min: '970px',
            max: '1199px'
        },
        'xl': {
            min: '1200px',
            max: null
        }
    };
    viewports.mediaQueries = {
        'xs-only': '(max-width: ' + viewports.breakpoints['xs']['max'] + ')',
        'sm-only': '(min-width: ' + viewports.breakpoints['sm']['min'] + ') and (max-width: ' + viewports.breakpoints['sm']['max'] + ')',
        'sm':      '(min-width: ' + viewports.breakpoints['sm']['min'] + ')',
        'md-only': '(min-width: ' + viewports.breakpoints['md']['min'] + ') and (max-width: ' + viewports.breakpoints['md']['max'] + ')',
        'md':      '(min-width: ' + viewports.breakpoints['md']['min'] + ')',
        'lg-only': '(min-width: ' + viewports.breakpoints['lg']['min'] + ') and (max-width: ' + viewports.breakpoints['lg']['max'] + ')',
        'lg':      '(min-width: ' + viewports.breakpoints['lg']['min'] + ')',
        'xl-only': '(min-width: ' + viewports.breakpoints['xl']['min'] + ')',
        'xl':      '(min-width: ' + viewports.breakpoints['xl']['min'] + ')',
    };
    // xs only
    enquire.register(viewports.mediaQueries['xs-only'], {
        match: function() { setViewport('xs'); setViewport('xs-only'); },
        unmatch: function() { unsetViewport('xs'); unsetViewport('xs-only'); }
    });

    // sm and larger
    enquire.register(viewports.mediaQueries['sm'], {
        match: function() { unsetViewport('xs-only'); setViewport('sm'); },
        unmatch: function() { unsetViewport('sm'); }
    });
    // sm only
    enquire.register(viewports.mediaQueries['sm-only'], {
        match: function() { setViewport('sm-only'); },
        unmatch: function() { unsetViewport('sm-only'); }
    });

    // md and larger
    enquire.register(viewports.mediaQueries['md'], {
        match: function() { setViewport('md'); },
        unmatch: function() { unsetViewport('md'); }
    });
    // md only
    enquire.register(viewports.mediaQueries['md-only'], {
        match: function() { setViewport('md-only'); },
        unmatch: function() { unsetViewport('md-only'); }
    });

    // lg and larger
    enquire.register(viewports.mediaQueries['lg'], {
        match: function() { setViewport('lg'); },
        unmatch: function() { unsetViewport('lg'); }
    });
    // lg only
    enquire.register(viewports.mediaQueries['lg-only'], {
        match: function() { setViewport('lg-only'); },
        unmatch: function() { unsetViewport('lg-only'); }
    });

    // xl and larger
    enquire.register(viewports.mediaQueries['xl'], {
        match: function() { setViewport('xl'); setViewport('xl-only'); },
        unmatch: function() { unsetViewport('xl'); unsetViewport('xl-only'); }
    });
</script>
<!-- Open X -->
<script type="text/javascript" src="//ox-d.bizjournals.servedbyopenx.com/w/1.0/jstag?nc=4635-BizJournals"></script>
<!-- Google Publisher Tags -->
<script>
var googletag = googletag || {};
googletag.cmd = googletag.cmd || [];
(function(){
    var gads = document.createElement('script');
    var useSSL = 'https:' == document.location.protocol;
    gads.src = (useSSL ? 'https:' : 'http:') + '//www.googletagservices.com/tag/js/gpt.js';
    var node = document.getElementsByTagName('script')[0];
    node.parentNode.insertBefore(gads, node);
})();
</script>
<!-- Google Analytics -->
<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-851607-1', '.bizjournals.com');
<?php if (isset($this->isCanonicalArticle) && ($this->isCanonicalArticle == true)): // canonical article ?>
  ga('send', 'pageview', {'dimension1':'Yes'});
<?php else: ?>
  ga('send', 'pageview');
<?php endif; ?>
</script>

<?php $marketCode = $this->getMarketCode(); ?>

<?php if ($this->showSitelink): ?>
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "<?= $this->getMainJournalName() ?>",
    "url": "http://www.bizjournals.com<?= ($marketCode != 'bizjournals') ? '/' . $marketCode : '' ?>",
    "potentialAction": {
        "@type": "SearchAction",
        "target": "http://www.bizjournals.com<?= ($marketCode != 'bizjournals') ? '/' . $marketCode : '' ?>/search/results?q={search_term_string}",
        "query-input": "required name=search_term_string"
    }
}
</script>
<?php endif; ?>

